spring:
    application:
        name: snapit-media-manager

    rabbitmq:
        host: a5e8bcb8399ee4d198dc303dab6e3970-549989597.us-east-1.elb.amazonaws.com
        port: 5672
        username: hexqueue
        password: 1xo4r9VIU4ARLW3f
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 200MB

aws:
    s3:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
        session-token: ${AWS_SESSION_TOKEN}
        region: ${AWS_REGION}
server:
    port: 28081

management:
    endpoint:
        health:
            probes:
                enabled: true
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
